name: Upload OpenAPI spec to Stainless and (Mintlify) docs repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download OpenAPI spec
        run: curl -o openapi/openapi.json https://mercury.dev.dream-ai.com/api/openapi.json
      - name: Push spec and config to Stainless and output documented spec
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'openapi/openapi.json'
          output_path: 'openapi/openapi.documented.json'
          project_name: 'hedra'
          commit_message: 'chore(api): update openapi specification'
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add openapi/openapi.json
          git add openapi/openapi.documented.json
          git commit -m 'chore: update documented OpenAPI spec'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
