name: Upload OpenAPI spec to Stainless and (Mintlify) docs repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download OpenAPI spec
        run: curl -o openapi/openapi.json https://mercury.dev.dream-ai.com/api/openapi.json
      - name: Push spec and config to Stainless and output documented spec
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'openapi/openapi.json'
          output_path: 'openapi/openapi.documented.json'
          project_name: 'hedra'
          commit_message: 'chore(api): update openapi specification'
