name: Upload OpenAPI spec to Stainless and (Mintlify) docs repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push spec and config to Stainless and output documented spec
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'api/openapi.json'
          output_path: 'api/openapi.documented.json'
          project_name: 'hedra'
          commit_message: 'chore(api): update openapi specification'
      - name: Push documented spec to docs repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'api/openapi.documented.json'
          destination_repo: 'hedra-labs/docs'
          destination_folder: 'api-reference' # (optional) the folder in the destination repository to place the file in, if not the root directory
          user_email: 'm.j.lbach@gmail.com' # the email associated with the GH token
          user_name: 'mjlbach' # the username associated with the GH token
          commit_message: 'chore: auto-updates from Stainless'
